---
- name: RedHat - Install logstash
  yum: name=logstash state=present update_cache=yes
  register: redhat_logstash_install_from_repo
  until: '"failed" not in redhat_logstash_install_from_repo'
  retries: 5
  delay: 10
