---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"

- include: java.yml
  when: logstash_java_install

- name: os-specific tasks
  include: "install-{{ansible_os_family}}.yml"

- include: config.yml

- name: restart logstash
  systemd:
    name: logstash
    state: started
    enabled: yes